sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=paulfantom/rpmbuilder
    - COPR_REPOSITORY=jsonnet
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=28
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=29
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=30
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7

services:
  - docker

install: true

script:
  - if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then .travis/check.sh; else docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}; fi

after_success:
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -K $encrypted_473e98cb5e1b_key -iv $encrypted_473e98cb5e1b_iv -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm; fi
